stages:
  - test
  - build
  - deploy

realizar_testes:
  stage: test
  image: node:17-alpine3.14
  script:
    - if [ "$CI_COMMIT_REF_NAME" != "docker" ]; then exit 0; fi  # Adicione esta linha para verificar a branch
    - cd app/
    - npm install
    - npm test
  artifacts:
    when: always
    reports:
        junit: app/junit.xml
  
build_images:
  stage: build
  needs:
    - realizar_testes
  script:
    - if [ "$CI_COMMIT_REF_NAME" != "docker" ]; then exit 0; fi  # verifica a branch
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker build -t marcelosoares92/gitlab-cicd-node:1.0 .
    - docker push marcelosoares92/gitlab-cicd-node:1.0

deploy_dev:
  stage: deploy
  needs:
    - build_images
  tags:
    - gcp
  script:
    - if [ "$CI_COMMIT_REF_NAME" != "docker" ]; then exit 0; fi  # verifica novamente a branch
    - docker run -d --name nodeapp -p 3000:3000 marcelosoares92/gitlab-cicd-node:1.0
